language: node_js
node_js:
  - "11.0"
cache:
  directories:
    - ./node_modules
branches:
  only:
    - master
install:
  - cd limeade && npm install
  - npm install -g codecov
script:
  - npm test ng-limeade -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - codecov -f ./coverage/*.json
after_success:
  - codecov
