language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - cd limeade
  - npm test ng-limeade -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
