language: node_js
node_js:
  - "11.0"
cache:
  directories:
    - ./node_modules
branches:
  only:
    - master
install:
  - npm install
#before_script:
#  - npm install -g @angular/cli
script:
  - cd limeade
  - npm test ng-limeade -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
