language: node_js
node_js:
  - "11.0"
cache:
  directories:
    - ./node_modules
branches:
  only:
    - master
install:
  - npm install
before_script:
  - npm install -g @angular/cli
  - npm install @angular-devkit/build-angular
  - npm install @angular-devkit/build-ng-packagr
  - npm install @angular/compiler
  - npm install @angular/compiler-cli
script:
  - cd limeade
  - ls
  - npm test ng-limeade -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
